<?php
/**
 * TL_ROOT/system/modules/googlesitemap/languages/ja/default.php 
 * 
 * Contao extension: googlesitemap 1.2.3 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['pageUpdateArticle']['0'] = "改訂日の更新";
$GLOBALS['TL_LANG']['MSC']['pageUpdateArticle']['1'] = "\"%s\"というアーティクルを保存しました。\"%s\"というページの変更日時も更新しますか?";
$GLOBALS['TL_LANG']['MSC']['pageUpdateContent']['0'] = "改訂日の更新";
$GLOBALS['TL_LANG']['MSC']['pageUpdateContent']['1'] = "\"%s\"というアーティクルのコンテンツ要素を保存しました。\"%s\"というページの変更日時も更新しますか?";
$GLOBALS['TL_LANG']['MSC']['applyPageUpdate'] = "改訂日を更新";
$GLOBALS['TL_LANG']['MSC']['cancelPageUpdate'] = "改訂日を維持";
$GLOBALS['TL_LANG']['MSC']['sitemap_changefreq']['always'] = "改訂日を常に更新(ページのアクセス毎に変更)";
$GLOBALS['TL_LANG']['MSC']['sitemap_changefreq']['hourly'] = "毎時";
$GLOBALS['TL_LANG']['MSC']['sitemap_changefreq']['daily'] = "毎日";
$GLOBALS['TL_LANG']['MSC']['sitemap_changefreq']['weekly'] = "毎週";
$GLOBALS['TL_LANG']['MSC']['sitemap_changefreq']['monthly'] = "毎月";
$GLOBALS['TL_LANG']['MSC']['sitemap_changefreq']['yearly'] = "毎年";
$GLOBALS['TL_LANG']['MSC']['sitemap_changefreq']['never'] = "更新しない(アーカイブ状態のURLに使用すべき)";
 
?>
