<?php
/**
 * TL_ROOT/system/modules/googlesitemap/languages/ja/tl_downloadarchivitems.php 
 * 
 * Contao extension: googlesitemap 1.2.3 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_downloadarchivitems']['addToSitemap']['0'] = "サイトマップに追加";
$GLOBALS['TL_LANG']['tl_downloadarchivitems']['addToSitemap']['1'] = "選択すると、このファイルをGoogleサイトマップのXMLに含めます。";
 
?>
