<?php
/**
 * TL_ROOT/system/modules/googlesitemap/languages/ja/tl_page.php 
 * 
 * Contao extension: googlesitemap 1.2.3 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['initialPage']['0'] = "初期ページ";
$GLOBALS['TL_LANG']['tl_page']['initialPage']['1'] = "ウェブサイトの最初のページの場合に選択してください。これを選択すると、リンクの作成にウェブサイトの(ページの)エイリアスを使用しません。";
$GLOBALS['TL_LANG']['tl_page']['sitemap_lastmod']['0'] = "最終更新日時";
$GLOBALS['TL_LANG']['tl_page']['sitemap_lastmod']['1'] = "ページを最後に更新した日時です。";
$GLOBALS['TL_LANG']['tl_page']['sitemap_ignore']['0'] = "サイトマップに無視";
$GLOBALS['TL_LANG']['tl_page']['sitemap_ignore']['1'] = "このページをXMLのサイトマップに表示しません。";
$GLOBALS['TL_LANG']['tl_page']['sitemap_changefreq']['0'] = "変更の頻度";
$GLOBALS['TL_LANG']['tl_page']['sitemap_changefreq']['1'] = "ページを変更すると考えられる頻度です。この値は検索エンジンに一般的な情報を提供しますが、ページをクロールする頻度に正確に関連付けられないかもしれません。";
$GLOBALS['TL_LANG']['tl_page']['sitemap_priority']['0'] = "優先度";
$GLOBALS['TL_LANG']['tl_page']['sitemap_priority']['1'] = "ウェブサイトの中で他のURLと比べた相対的なURLの優先度です。この値は他のサイトとページを比較する際には何の影響はなく、もっとも好ましく検索エンジンがページをクロールする順序を決められるように、どのページを重要と想定しているか検索エンジンに知らせるだけです。";
$GLOBALS['TL_LANG']['tl_page']['sitemapHeader']['0'] = "サイトマップのヘッダー";
$GLOBALS['TL_LANG']['tl_page']['sitemapHeader']['1'] = "このサイトマップにXSLのスタイルシートのような独自のXML定義を追加できます。";
 
?>
