<?php
/**
 * TL_ROOT/system/modules/googlesitemap/languages/ja/tl_settings.php 
 * 
 * Contao extension: googlesitemap 1.2.3 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2008-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['updatePageLastmod']['0'] = "ページの更新日時を更新";
$GLOBALS['TL_LANG']['tl_settings']['updatePageLastmod']['1'] = "選択すると、アーティクルとコンテンツ要素を保存するときに、ページの更新日時を更新するかどうか聞いてくるようになります。";
$GLOBALS['TL_LANG']['tl_settings']['noqueryPageLastmod']['0'] = "自動的に更新日時を更新";
$GLOBALS['TL_LANG']['tl_settings']['noqueryPageLastmod']['1'] = "ページの更新日時を更新しなければならないときの確認を求めません。";
$GLOBALS['TL_LANG']['tl_settings']['pingGoogle']['0'] = "Googleにpingを実行";
$GLOBALS['TL_LANG']['tl_settings']['pingGoogle']['1'] = "サイトマップを変更したとき、常にGoogleに通知します。 <a href=\"http://www.google.com/support/webmasters/bin/answer.py?hl=en&answer=34609\" onclick=\"window.open(this.href); return false\">詳細を読む</a>。";
 
?>
